### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by MStypulkowski** [AlexMaOLS/EluCD#1]
Hi, thanks for your work!

I have two questions about the method:
1. For EDM guidance, is there any reason you apply it only to the main step and not the 2nd order correction?
2. Have you tried using any pre-trained models for guidance other than classifiers (following https://arxiv.org/abs/2302.07121)?

**Comment by AlexMaOLS** [comment]
Hi MStypulkowski, thank you for your questions. 

1, Regarding EDM guidance, we appreciate your interesting point about incorporating extra classifier guidance in the 2nd order correction. We did not add it not on purposely, but we believe that showcasing the 1st order is sufficient to demonstrate the potential of off-the-shelf guidance in enhancing EDM generation quality without significant additional sampling time (as shown in Table 8 of our paper). We value your suggestions and will discover them more in future research. 

2, Yes, we explore the use of off-the-shelf CLIP model for text-to-image guidance. Unlike Universal guidance diffusion, [our research](https://arxiv.org/abs/2310.11311) discovered that simply increasing recurrent guidance operations within the sampling step did not significantly enhance generation quality (as shown in Table 1 of our paper), while the well-calibrated design proved to be crucial. In section 5.4, we demonstrate the effectiveness of applying off-the-shelf CLIP guided diffusion with our proposed designs, such as the $Sin$ factor guidance schedule, which led to notable improvements in CLIP scores (shown in Figure 7).
